name: CasinoManager
main: com.nhksos.quantumrex.Casino.CasinoManager
version: 0.11
website: http://github.com/quantumrex/Casino
author: quantumrex

description: >
             Provides an interface for in game management of a 
             Casino consisting of basic mini-games and other 
             such attractions

commands:
  makecasino:
    description: Creates a Casino for the issuing user
    usage: /<command> 
    aliases: [mcasino,mc]
  makemachine:
    description: Creates a machine in the current user's casino
    usage: /<command> 
    aliases: [mmachine,mmach,mm]
  test:
    description: Tests all machines in the casino for visual functionality
    usage: /<command> 
    aliases: [t]
  destroycasino:
    description: Tests all machines in the casino for visual functionality
    usage: /<command> 
    aliases: [dcasino,dc]