global:
    world:
    objects:
        path:       plugins/CasinoManager/
        casinos:    casinos.sav
        games:      games.sav
        owners:     owners.sav
        activators: activators.sav
            
players:
    quantumrex:
        wins:    0
        losses:  0
        total:   0
        balance: 0